### ISSUE TITLE
Large scale sonobuoy test coverage improvements : print out the e2e.log file, tests backends separately

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/kpng#109]
Now that @nehaLohia27 has added sonobuoy stuff with friedrich, we can follow on : 

- kubectl get pods -n sonobuoy
- kubectl logs e2e... -n sonobuoy # <-- print out the full test log

this will help in case of tests failures.

After that lets triple our GH actions running sonobuoy separately for each backend./ 

- `e2e-focus=sig-network` and `e2e-skip=Disruptive|Slow` and then , we can see what tests break on which proxies

**Comment by nehaLohia27** [comment]
@jayunit100 Sure I will add these test cases

**Comment by nehaLohia27** [comment]
@jayunit100 Can you please assign this issue to me

**Comment by nehaLohia27** [comment]
I have tried to run few sonobuoy tests using flags like e2e-focus=sig-network and e2e-skip=Disruptive.. The tests did not complete successfully and failed with below erorr

18:11:51  systemd-logs  kpng-proxy-control-plane  complete           
18:11:51  systemd-logs     kpng-proxy-worker  complete           
18:11:51  systemd-logs     kpng-proxy-worker2  complete           
18:11:51       e2e           global  running           
18:11:51 
18:11:51 Sonobuoy is still running. Runs can take 60 minutes or more depending on cluster and plugin configuration.
18:12:12       e2e           global  running      1/212 (0 failures)
...
18:13:36       e2e           global  running      2/212 (1 failures)
18:14:21 Failed to check status of the aggregator: failed to get namespace sonobuoy: Get "https://0.0.0.0:49794/api/v1/namespaces/sonobuoy": http2: client connection lost
ERRO[0170] error attempting to run sonobuoy: waiting for run to finish: failed to get status: failed to get namespace sonobuoy: Get "https://0.0.0.0:49794/api/v1/namespaces/sonobuoy": http2: client connection lost]

when I run kubectl get ns . getting below error:
Unable to connect to the server: net/http: TLS handshake timeout


Not sure if this is the problem with my cluster or macbook.. This is blocking the sonobuoy tests execution ..

**Comment by nehaLohia27** [comment]
As per the discussion we will use e2e test plugin in the CI builds and not sonobuoy plugin.
@jayunit100 @mcluseau Can we close this issue ?
