### ISSUE TITLE
Build first PROW job w @antonio!

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/kpng#111]
@aojea has offered to pair on building the first prow job with us.

@nehaLohia27 can you join forces on that front?

- 1 backend: `iptables` ? 
- initial test: maybe something 

```e2e.test --provider=local --kubeconfig=/home/ubuntu/.kube/config --dump-logs-on-failure=false --ginkgo.focus="sig-network|services" --ginkgo.skip="rolling|Slow|6" --ginkgo.dryRun=true```

**Comment by nehaLohia27** [comment]
sure @jayunit100 Once conformance tests work is done, I will start looking at this also..

**Comment by aojea** [comment]
No need for prow for now, github actions work fine at this point and there still e2e tests that need to be fixed.

It seems that DNS and udp services are not working fine?

Anyway, you have a PR here as basis https://github.com/kubernetes-sigs/kpng/pull/118

and results here https://github.com/aojea/kpng/actions/runs/1481423799

**Comment by nehaLohia27** [comment]
@aojea @jayunit100 I am also testing the github actions to include sonobuoy tests for e2e plugin with flags like e2e-focus=sig-network and e2e-skip = Disruptive. There are still more flags to be tested. I assume the same tests will be called here right ? There are failures which need to be analysed and fixed..

**Comment by jayunit100** [comment]
#118 <-- initial MR that will bring us closer to idiomatic PROW style jobs
