### ISSUE TITLE
The /hack/README.md needs to be redone.

### ISSUE THREAD

**Issue by friedrichwilken** [kubernetes-sigs/kpng#124]
In the recent weeks, a lot was added to `/hack`. This is hardly documented at all, so the [README](https://github.com/kubernetes-sigs/kpng/blob/master/hack/README.md) is pretty outdated, and deserves some proper rework.

1. As @knabben already [mentioned](https://github.com/kubernetes-sigs/kpng/pull/121#discussion_r757173491), add a `tree` output of the dir and give little explanation of what to find here.
2. Give an overview of all the tests and how to execute them. Mention where we use them in CI
3. Give some more details about what the tests actually do.

This could be an interesting issue for someone new who wants to get into the CI part of the project. @nehaLohia27 and I could provide the details to that person.

**Comment by aahemm** [comment]
Hi @FriedrichWilken,
I would like to contribute to the docs and learn more about the project. Where can we start?
