### ISSUE TITLE
a self-awareness "interface" for NFT pod 

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/kpng#13]
The NFT tables pod is susceptible to naughty bhaviour when iptables is installed.

To remediate this, and also, to create a precendent for other service proxy backends, lets:

- add a "SystsemCheck()" or similar implementatino in the NFT backend
- Have it verify that *all* `iptables` rules (i.e. see the ones in #12) are empty
- if iptables rules non-empty print continous warnings that are extremely idiot-proof , i.e. 
`warning: ip routing may not work properly due to mutliple kernel firewalls !` 

This will make it really easy for folks struggling w/ the incompatibilities (iptables, legacy iptables, and nft, and so on) to know why loadbalancing rules written by NFT arent getting honored.

**Comment by jayunit100** [comment]
@mcluseau let us know if any details we need to update here

**Comment by hanlins** [comment]
Had some discussion with @mcluseau, later we might introduce subcommand `to-best-fit` which selects the best sink backend based on the system check results. Will add some functionality here to check whether the `nft` requirement is met. In the `nft` sink, will invoke this backend but won't error out if the system is not compatible. We will leave this flexibility of using `nft` backend to the users, only leave some logs the potential compatibility issues.

**Comment by jayunit100** [comment]
make sure those logs are really explicit and repeated periodically :)
