### ISSUE TITLE
NodePort service Conformance test failing

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/kpng#136]
https://github.com/kubernetes-sigs/kpng/issues/132

Looks like this is the most obvious interesting test failure we currnetly have, reported in one of @nehaLohia27 's test jobs

```
should be able to create a functioning NodePort service [Conformance] 
```

Good opportunity to learn some kube proxy internals for @anusha94

**Comment by nehaLohia27** [comment]
@anusha94 This tests is also passing in github CI now. 
Refer this yesterday build. 
https://github.com/kubernetes-sigs/kpng/runs/4607873476?check_suite_focus=true

**Comment by anusha94** [comment]
Thanks @nehaLohia27 !
We can monitor it for few more days and see if it fails again (to verify if its flaky or not). We can look at increasing timeout etc if required.
