### ISSUE TITLE
[sig-network] [Services]  should create endpoints for unready pods 

### ISSUE THREAD

**Issue by nehaLohia27** [kubernetes-sigs/kpng#140]
Debugging this test failure along in kpng cluster with iptables

**Comment by nehaLohia27** [comment]
./ginkgo --focus="should create endpoints for unready pods" /Users/nlohia/Documents/neha/kubernetes/_output/bin/e2e.test -- --kubeconfig="/Users/nlohia/Documents/neha/friedrich/kpng/hack/temp/e2e/bin/kubeconfig.conf" --provider=local --dump-logs-on-failure=false --report-dir=reports --disable-log-dump=true
I1205 14:35:15.224826    2584 e2e.go:130] Starting e2e run "0ca2b366-0a92-45f2-a594-666426ad3899" on Ginkgo node 1
{"msg":"Test Suite starting","total":1,"completed":0,"skipped":0,"failed":0}
Running Suite: Kubernetes e2e suite
===================================
Random Seed: 1638695114 - Will randomize all specs
Will run 1 of 7031 specs

Dec  5 14:35:16.824: INFO: >>> kubeConfig: /Users/nlohia/Documents/neha/friedrich/kpng/hack/temp/e2e/bin/kubeconfig.conf
Dec  5 14:35:16.835: INFO: Waiting up to 30m0s for all (but 0) nodes to be schedulable
Dec  5 14:35:16.886: INFO: Waiting up to 10m0s for all pods (need at least 0) in namespace 'kube-system' to be running and ready
Dec  5 14:35:16.930: INFO: 12 / 12 pods in namespace 'kube-system' are running and ready (0 seconds elapsed)
Dec  5 14:35:16.930: INFO: expected 2 pod replicas in namespace 'kube-system', 2 are Running and Ready.
Dec  5 14:35:16.930: INFO: Waiting up to 5m0s for all daemonsets in namespace 'kube-system' to start
Dec  5 14:35:16.947: INFO: 3 / 3 pods ready in namespace 'kube-system' in daemonset 'kindnet' (0 seconds elapsed)
Dec  5 14:35:16.947: INFO: 3 / 3 pods ready in namespace 'kube-system' in daemonset 'kpng' (0 seconds elapsed)
Dec  5 14:35:16.947: INFO: e2e test version: v1.23.0-alpha.4.323+45533aef3ae1da-dirty
Dec  5 14:35:16.950: INFO: kube-apiserver version: v1.22.2
Dec  5 14:35:16.950: INFO: >>> kubeConfig: /Users/nlohia/Documents/neha/friedrich/kpng/hack/temp/e2e/bin/kubeconfig.conf
Dec  5 14:35:16.961: INFO: Cluster IP family: ipv4
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
------------------------------
[sig-network] Services 
  should create endpoints for unready pods
  /Users/nlohia/Documents/neha/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/service.go:1648
[BeforeEach] [sig-network] Services
  /Users/nlohia/Documents/neha/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:185
STEP: Creating a kubernetes client
Dec  5 14:35:16.964: INFO: >>> kubeConfig: /Users/nlohia/Documents/neha/friedrich/kpng/hack/temp/e2e/bin/kubeconfig.conf
STEP: Building a namespace api object, basename services
W1205 14:35:17.209195    2584 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
Dec  5 14:35:17.209: INFO: No PodSecurityPolicies found; assuming PodSecurityPolicy is disabled.
STEP: Waiting for a default service account to be provisioned in namespace
[BeforeEach] [sig-network] Services
  /Users/nlohia/Documents/neha/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/service.go:749
[It] should create endpoints for unready pods
  /Users/nlohia/Documents/neha/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/service.go:1648
STEP: creating RC slow-terminating-unready-pod with selectors map[name:slow-terminating-unready-pod]
STEP: creating Service tolerate-unready with selectors map[name:slow-terminating-unready-pod testid:tolerate-unready-b183859e-d77c-4d29-9f4c-3c4507d76d2b]
STEP: Verifying pods for RC slow-terminating-unready-pod
Dec  5 14:35:17.269: INFO: Pod name slow-terminating-unready-pod: Found 0 pods out of 1
Dec  5 14:35:22.283: INFO: Pod name slow-terminating-unready-pod: Found 1 pods out of 1
STEP: ensuring each pod is running
STEP: trying to dial each unique pod
Dec  5 14:35:22.341: INFO: Controller slow-terminating-unready-pod: Got non-empty result from replica 1 [slow-terminating-unready-pod-xddhq]: "NOW: 2021-12-05 09:05:22.342577279 +0000 UTC m=+3.723531183", 1 of 1 required successes so far
STEP: Waiting for endpoints of Service with DNS name tolerate-unready.services-9071.svc.cluster.local
Dec  5 14:35:22.341: INFO: Creating new exec pod
Dec  5 14:35:26.370: INFO: Running '/usr/local/bin/kubectl --server=https://127.0.0.1:58003 --kubeconfig=/Users/nlohia/Documents/neha/friedrich/kpng/hack/temp/e2e/bin/kubeconfig.conf --namespace=services-9071 exec execpod-ng2b2 -- /bin/sh -x -c curl -q -s --connect-timeout 300 http://tolerate-unready.services-9071.svc.cluster.local:80/'
Dec  5 14:35:31.783: INFO: rc: 6
Dec  5 14:35:31.783: INFO: expected un-ready endpoint for Service slow-terminating-unready-pod, stdout: , err error running /usr/local/bin/kubectl --server=https://127.0.0.1:58003 --kubeconfig=/Users/nlohia/Documents/neha/friedrich/kpng/hack/temp/e2e/bin/kubeconfig.conf --namespace=services-9071 exec execpod-ng2b2 -- /bin/sh -x -c curl -q -s --connect-timeout 300 http://tolerate-unready.services-9071.svc.cluster.local:80/:
Command stdout:

stderr:
+ curl -q -s --connect-timeout 300 http://tolerate-unready.services-9071.svc.cluster.local:80/
command terminated with exit code 6

error:
exit status 6
Dec  5 14:35:33.786: INFO: Running '/usr/local/bin/kubectl --server=https://127.0.0.1:58003 --kubeconfig=/Users/nlohia/Documents/neha/friedrich/kpng/hack/temp/e2e/bin/kubeconfig.conf --namespace=services-9071 exec execpod-ng2b2 -- /bin/sh -x -c curl -q -s --connect-timeout 300 http://tolerate-unready.services-9071.svc.cluster.local:80/'
Dec  5 14:35:39.375: INFO: rc: 6
Dec  5 14:35:39.375: INFO: expected un-ready endpoint for Service slow-terminating-unready-pod, stdout: , err error running /usr/local/bin/kubectl --server=https://127.0.0.1:58003 --kubeconfig=/Users/nlohia/Documents/neha/friedrich/kpng/hack/temp/e2e/bin/kubeconfig.conf --namespace=services-9071 exec execpod-ng2b2 -- /bin/sh -x -c curl -q -s --connect-timeout 300 http://tolerate-unready.services-9071.svc.cluster.local:80/:
Command stdout:

stderr:
+ curl -q -s --connect-timeout 300 http://tolerate-unready.services-9071.svc.cluster.local:80/
command terminated with exit code 6

**Comment by nehaLohia27** [comment]
![image](https://user-images.githubusercontent.com/4365624/144743899-b3854f90-65cb-4a47-84e0-c8505fe7b418.png)

**Comment by jayunit100** [comment]
# step 1 run ginkgo
```
./ginkgo --focus="should create endpoints for unready pods" /Users/nlohia/Documents/neha/kubernetes/_output/bin/e2e.test -- --kubeconfig="/Users/nlohia/Documents/neha/friedrich/kpng/hack/temp/e2e/bin/kubeconfig_calico.conf" --provider=local --dump-logs-on-failure=false --report-dir=reports --disable-log-dump=true
```

# Step 2 .. logs 
```
I1205 12:15:41.251828 78896 e2e.go:130] Starting e2e run "44463cb4-6712-4055-981c-74b2ba47995f" on Ginkgo node 1
{"msg":"Test Suite starting","total":1,"completed":0,"skipped":0,"failed":0}
Running Suite: Kubernetes e2e suite
Random Seed: 1638695114 - Will randomize all specs
Will run 1 of 7031 **specs

Dec 5 14:35:16.824: INFO: >>> kubeConfig: /Users/nlohia/Documents/neha/friedrich/kpng/hack/temp/e2e/bin/kubeconfig.conf
Dec 5 14:35:16.835: INFO: Waiting up to 30m0s for all (but 0) nodes to be schedulable
Dec 5 14:35:16.886: INFO: Waiting up to 10m0s for all pods (need at least 0) in namespace 'kube-system' to be running and ready
Dec 5 14:35:16.930: INFO: 12 / 12 pods in namespace 'kube-system' are running and ready (0 seconds elapsed)
Dec 5 14:35:16.930: INFO: expected 2 pod replicas in namespace 'kube-system', 2 are Running and Ready.
Dec 5 14:35:16.930: INFO: Waiting up to 5m0s for all daemonsets in namespace 'kube-system' to start
Dec 5 14:35:16.947: INFO: 3 / 3 pods ready in namespace 'kube-system' in daemonset 'kindnet' (0 seconds elapsed)
Dec 5 14:35:16.947: INFO: 3 / 3 pods ready in namespace 'kube-system' in daemonset 'kpng' (0 seconds elapsed)
Dec 5 14:35:16.947: INFO: e2e test version: v1.23.0-alpha.4.323+45533aef3ae1da-dirty
Dec 5 14:35:16.950: INFO: kube-apiserver version: v1.22.2
Dec 5 14:35:16.950: INFO: >>> kubeConfig: /Users/nlohia/Documents/neha/friedrich/kpng/hack/temp/e2e/bin/kubeconfig.conf
Dec 5 14:35:16.961: INFO: Cluster IP family: ipv4
```

# Results 

```
[sig-network] Services
should create endpoints for unready pods
/Users/nlohia/Documents/neha/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/service.go:1648
[BeforeEach] [sig-network] Services
/Users/nlohia/Documents/neha/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:185
STEP: Creating a kubernetes client
Dec 5 14:35:16.964: INFO: >>> kubeConfig: /Users/nlohia/Documents/neha/friedrich/kpng/hack/temp/e2e/bin/kubeconfig.conf
STEP: Building a namespace api object, basename services
W1205 14:35:17.209195 2584 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
Dec 5 14:35:17.209: INFO: No PodSecurityPolicies found; assuming PodSecurityPolicy is disabled.
STEP: Waiting for a default service account to be provisioned in namespace
[BeforeEach] [sig-network] Services
/Users/nlohia/Documents/neha/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/service.go:749
[It] should create endpoints for unready pods
/Users/nlohia/Documents/neha/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/service.go:1648
STEP: creating RC slow-terminating-unready-pod with selectors map[name:slow-terminating-unready-pod]
STEP: creating Service tolerate-unready with selectors map[name:slow-terminating-unready-pod testid:tolerate-unready-b183859e-d77c-4d29-9f4c-3c4507d76d2b]
STEP: Verifying pods for RC slow-terminating-unready-pod
Dec 5 14:35:17.269: INFO: Pod name slow-terminating-unready-pod: Found 0 pods out of 1
Dec 5 14:35:22.283: INFO: Pod name slow-terminating-unready-pod: Found 1 pods out of 1
STEP: ensuring each pod is running
STEP: trying to dial each unique pod
Dec 5 14:35:22.341: INFO: Controller slow-terminating-unready-pod: Got non-empty result from replica 1 [slow-terminating-unready-pod-xddhq]: "NOW: 2021-12-05 09:05:22.342577279 +0000 UTC m=+3.723531183", 1 of 1 required successes so far
STEP: Waiting for endpoints of Service with DNS name tolerate-unready.services-9071.svc.cluster.local
Dec 5 14:35:22.341: INFO: Creating new exec pod
Dec 5 14:35:26.370: INFO: Running '/usr/local/bin/kubectl --server=https://127.0.0.1:58003 --kubeconfig=/Users/nlohia/Documents/neha/friedrich/kpng/hack/temp/e2e/bin/kubeconfig.conf --namespace=services-9071 exec execpod-ng2b2 -- /bin/sh -x -c curl -q -s --connect-timeout 300 http://tolerate-unready.services-9071.svc.cluster.local:80/'
Dec 5 14:35:31.783: INFO: rc: 6
Dec 5 14:35:31.783: INFO: expected un-ready endpoint for Service slow-terminating-unready-pod, stdout: , err error running /usr/local/bin/kubectl --server=https://127.0.0.1:58003 --kubeconfig=/Users/nlohia/Documents/neha/friedrich/kpng/hack/temp/e2e/bin/kubeconfig.conf --namespace=services-9071 exec execpod-ng2b2 -- /bin/sh -x -c curl -q -s --connect-timeout 300 http://tolerate-unready.services-9071.svc.cluster.local:80/:
Command stdout:

stderr:

curl -q -s --connect-timeout 300 http://tolerate-unready.services-9071.svc.cluster.local:80/
command terminated with exit code 6
error:
exit status 6
Dec 5 14:35:33.786: INFO: Running '/usr/local/bin/kubectl --server=https://127.0.0.1:58003 --kubeconfig=/Users/nlohia/Documents/neha/friedrich/kpng/hack/temp/e2e/bin/kubeconfig.conf --namespace=services-9071 exec execpod-ng2b2 -- /bin/sh -x -c curl -q -s --connect-timeout 300 http://tolerate-unready.services-9071.svc.cluster.local:80/'
Dec 5 14:35:39.375: INFO: rc: 6
Dec 5 14:35:39.375: INFO: expected un-ready endpoint for Service slow-terminating-unready-pod, stdout: , err error running /usr/local/bin/kubectl --server=https://127.0.0.1:58003 --kubeconfig=/Users/nlohia/Documents/neha/friedrich/kpng/hack/temp/e2e/bin/kubeconfig.conf --namespace=services-9071 exec execpod-ng2b2 -- /bin/sh -x -c curl -q -s --connect-timeout 300 http://tolerate-unready.services-9071.svc.cluster.local:80/:
```

stderr:
```
curl -q -s --connect-timeout 300 http://tolerate-unready.services-9071.svc.cluster.local:80/
command terminated with exit code 6
```

**Comment by jayunit100** [comment]
If we do 

- #141
- #142  

AND we make sure that we support the 
```
Spec: v1.ServiceSpec{
				Selector: t.Labels,
				Ports: []v1.ServicePort{{
					Name:       "http",
					Port:       int32(port),
					TargetPort: intstr.FromInt(port),
				}},
				PublishNotReadyAddresses: true <-- THIS ONE !!!
			}, 
```

This test will start passing ! 

Great work @nehaLohia27 helping to find this corner case !!!
