### ISSUE TITLE
Document updating protobuf datamodel + add it to CI and kpng local up

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/kpng#143]
We dont have instructions on how to update the protobuf generator.

- updated-protobuf.sh script: updates the protobuf generated golang programs...
- verify-protobuf.sh script: runs update, checks that theres NO CHANGE to the structs...
- REAMDE.md on using them...

As @nehaLohia27 and @anusha94 dig into #140 and #141, lets add a README.md
in the part of our code that translates the protobuf from k8s services to v1.localnet services, so that future datamodel changes are easy to make. 

xref https://developers.google.com/protocol-buffers/docs/reference/go-generated for folks new to protobuf

**Comment by nehaLohia27** [comment]
Command used

protoc --go_out=. --go-grpc_out=. --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative services.proto 


This generates the 2 files
services.pb.go
services_grpc.pb.go

**Comment by jayunit100** [comment]
Something like...
```
   sudo apt-get install protobuf-compiler\n
   sudo apt install protoc-gen-go\n
   apt-get search protoc-gen-go\n
   apt search protoc-gen-go\n
```
And 
```
protoc -I=. --go_out=api/localnetv1/ api/localnetv1/services.proto
```

should do it ...
