### ISSUE TITLE
ConntrackModule

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/kpng#157]
# Adding a conntracksubsystemmanagementSINK
  
gastank!

Right now we dont manage cleanup of conntrack...

We can manage it in a way thats orthogonal to any of the backends, by making a conntrack module based on https://github.com/kubernetes/kubernetes/blob/master/pkg/util/conntrack/conntrack.go.

![image](https://user-images.githubusercontent.com/826111/146582628-2715baca-ab7b-4c8f-82d0-1b6fe58f13c6.png)

This will basically be like a "separate backend" that runs in the same process , i.e. it wont share any memory w/ the "actual" backend, but it will be glued on when things start up.

**Comment by qabpea** [comment]
As in included by the backends that use the conntracker?

**Comment by mcluseau** [comment]
Yes :)

**Comment by qabpea** [comment]
Issue #174 is caused by this defect

**Comment by hanamantagoudvk** [comment]
i will start working on this..

**Comment by jayunit100** [comment]
Whoever wants to work on this, we have a detailed description of some of the conntrack problems here  https://github.com/kubernetes-sigs/kpng/issues/235 .... might be a good place to get started

**Comment by jayunit100** [comment]
mikael said he can dig into this one for now
/assign @mcluseau

**Comment by mcluseau** [comment]
I think it's done at least since #264  ;)
/close
