### ISSUE TITLE
{IPv4-iptables] [e2e] Fail:  Service session affinity 

### ISSUE THREAD

**Issue by qabpea** [kubernetes-sigs/kpng#196]
The e2e test fail for some of the affinity tests.
The tests are found at https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/service.go#L1795-L1888.

Two of the tests with ClusterIP affinity fails right now
[Fail] [sig-network] Services [It] should have session affinity work for service with type clusterIP [LinuxOnly] [Conformance]
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/service.go#L1803 

[Fail] [sig-network] Services [It] should have session affinity timeout work for service with type clusterIP [LinuxOnly] [Conformance] 
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/service.go#L1819

**Comment by qabpea** [comment]
[fail-10.txt](https://github.com/kubernetes-sigs/kpng/files/7871886/fail-10.txt)

**Comment by hanamantagoudvk** [comment]
assigned it to vivek as he is handling iptable backend
