### ISSUE TITLE
[e2e] Fail: Services [It] should be able to create a functioning NodePort service

### ISSUE THREAD

**Issue by qabpea** [kubernetes-sigs/kpng#203]
Test can be found here:
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/service.go#L1165-L1191
Description:
Create a TCP NodePort service, and test reachability from a client Pod.
The client Pod MUST be able to access the NodePort service by service name and cluster
IP on the service port, and on nodes' internal and external IPs on the NodePort.

**Comment by nehaLohia27** [comment]
e2e tests failing in ipv4 and ipvs backend. 
https://github.com/kubernetes-sigs/kpng/runs/4779261817?check_suite_focus=true
