### ISSUE TITLE
Replace IPTables ServiceChangeTracker w/ the new DiffStore...

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/kpng#223]
Now that the new DiffStore is completed, we can
consider moving the old iptables (serviceChangeTracker) implementation 
out as part of the #215 stuff.

**Comment by jayunit100** [comment]
See https://github.com/kubernetes-sigs/kpng/commit/c01d4ba3ce61ea05cbbb40292dc57ee45733c517 as an example...

**Comment by jayunit100** [comment]
(we can get iptables v6 and v4 to 100% passing before doing this if we want, that way we know wether this breaks anything along the way)

**Comment by anusha94** [comment]
Ooh this issue looks interesting
