### ISSUE TITLE
kpng version shows unknown 

### ISSUE THREAD

**Issue by dougsland** [kubernetes-sigs/kpng#228]
# Issue
`kpng version` should show the git tag/hash id which the build was based or the release version.

Reference:
[1] https://github.com/kubernetes-sigs/kpng/pull/219/commits/2a70684c55a5351d903d6b42d277378ac889c982#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R20

[2] https://github.com/kubernetes-sigs/kpng/pull/219/commits/2a70684c55a5351d903d6b42d277378ac889c982#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R21

**Comment by aahemm** [comment]
Hi @kundan2707,
it seems that you were working on this issue a while ago. Please let me know if it is not the case now. Thanks.

**Comment by uablrek** [comment]
I have added it to `hack/go-build` in PR https://github.com/kubernetes-sigs/kpng/pull/306.

**Comment by jaehnri** [comment]
I'm not sure if this issue is fixed or not. @uablrek, I just tested and it looks like this is not fixed. These were the steps I used:

```bash
docker build -t jaehnri/kpng:ipvs ./      
IMAGE=jaehnri/kpng:ipvs PULL=Never BACKEND=ipvs ./hack/kpng-local-up.sh
kind load docker-image jaehnri/kpng:ipvs --name=kpng-proxy

kubectl exec -ti kpng-747wb -n kube-system -c kpng -- sh
/ # ./bin/kpng version
I0107 15:29:23.563584      85 command_builder.go:139] Appending discovered command to-ebpf
I0107 15:29:23.563640      85 command_builder.go:139] Appending discovered command to-iptables
I0107 15:29:23.563837      85 command_builder.go:139] Appending discovered command to-ipvs
I0107 15:29:23.563952      85 command_builder.go:139] Appending discovered command to-nft
I0107 15:29:23.563961      85 command_builder.go:139] Appending discovered command to-userspacelin
...
I0107 15:29:23.564421      85 command_builder.go:139] Appending discovered command to-ebpf
I0107 15:29:23.564456      85 command_builder.go:139] Appending discovered command to-iptables
I0107 15:29:23.564639      85 command_builder.go:139] Appending discovered command to-ipvs
I0107 15:29:23.564704      85 command_builder.go:139] Appending discovered command to-nft
I0107 15:29:23.564748      85 command_builder.go:139] Appending discovered command to-userspacelin
(unknown)

/ # 
```

/assign

**Comment by uablrek** [comment]
The version must be set at build-time. It's still in `hack/go-build`, but I guess `kpng` is not built that way any more.
