### ISSUE TITLE
Add unit tests for iptables backend

### ISSUE THREAD

**Issue by rajaskakodkar** [kubernetes-sigs/kpng#258]
Unit tests need to be added for iptables backend - https://github.com/kubernetes-sigs/kpng/tree/master/backends/iptables

For reference: Unit tests in iptables mode of kube-proxy https://github.com/kubernetes/kubernetes/tree/master/pkg/proxy/iptables

**Comment by yashsingh74** [comment]
Created a PR- https://github.com/kubernetes-sigs/kpng/pull/284
