### ISSUE TITLE
Add unit tests for ipvs backend

### ISSUE THREAD

**Issue by rajaskakodkar** [kubernetes-sigs/kpng#259]
Unit tests need to be added for ipvs backend - https://github.com/kubernetes-sigs/kpng/tree/master/backends/ipvs-as-sink

For reference: Unit tests in ipvs mode for kube proxy - https://github.com/kubernetes/kubernetes/tree/master/pkg/proxy/ipvs

**Comment by shaneutt** [comment]
@yashsingh74 it sounded like at one point in the past you wanted to take this one on, is that still the case? Let us know if you're OK with us assigning someone else. :vulcan_salute:
