### ISSUE TITLE
Add TopologyAwareHints to the KPNG brain

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/kpng#262]
We use the old topology API currently: https://github.dev/kubernetes-sigs/kpng/blob/990877f589ef015a24562a03099084baff2be8fb/server/jobs/kube2store/slice-event-handler.go#L1 

```
	h.s.Update(func(tx *proxystore.Tx) {
		klog.V(3).Info("service ", service.Namespace, "/", service.Name, " topology key: ", svc.Spec.TopologyKeys)
		tx.SetService(service, svc.Spec.TopologyKeys)
		h.updateSync(proxystore.Services, tx)
	})
```

# Problem

I think these APIs start dissapearing in 1.22+, as i recently learned when updating the codebase to 1.23...  So we need to move to the new API to avoid compilation breaking for KPNG w/ 1.23 versions+

https://kubernetes.io/docs/concepts/services-networking/topology-aware-hints/

# Solution

So To solve this issue : 

- Look at how KPNG sends Topology hints to backend and document this
- Run KPNG and observe results of E2E Tests for Topology services
- Remove the above code that sets keys or replace w string[], confirm that theres some kind of regression.
- Now update to the 1.23 API, and re run these tests, observe the same regression
- Migrate the svc.Spec.TopologyKeys code to use the new Topology Hints API constructs, described in the blog post above.

This shouldnt be brutally difficult - it only touches the KPNG brain, i think... but I'm not 100% sure.  is a good issue for someone to own end to end that wants to get involved in KPNG and is looking for a medium difficulty challenge .

Since the  KPNG communitys bandwidth is a little limeited, it would i think be best to do this issue all in one, s o that we can review it in its holistic completion., as opposed to breaking it out into separate commits, especially since it involves breaking the old API  for how  kpng worked and requires looking at how it effects all backends --- and also --- i wonder if we need to make new upstream e2e tests ?

**Comment by gauravkghildiyal** [comment]
@jayunit100 Looks like we've migrated to `.24` already. Can you confirm if this is issue is not valid anymore?

**Comment by mcluseau** [comment]
TopologyAwareHints are not done yet, I just removed the TopologyKeys to be
1.24-compatible.
