### ISSUE TITLE
Add make target for grpc compilation

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/kpng#282]
we need to:
- document how to build our GRPC stubs which live in https://github.com/kubernetes-sigs/kpng/blob/master/api/localnetv1/services.proto 
```
apt install protoc

protoc -I=./protobuf 
--go_out=plugins=grpc:./protobuf 
./protobuf/kpng.proto

... 
```

- make a hack/generate-grpc.sh script
- make a hack/verify-grpc.sh script
- add a ci job that runs "generate-grpc.sh" and then compares (diffs) content w/ verify-rpc.sh -> fails if different

/good-first-issue

**Comment by jayunit100** [comment]
we need to:
- document how to build our GRPC stubs which live in https://github.com/kubernetes-sigs/kpng/blob/master/api/localnetv1/services.proto 
```
apt install protoc

protoc -I=./protobuf --go_out=plugins=grpc:./protobuf ./protobuf/kpng.proto

... 
```

- make a hack/generate-grpc.sh script
- make a hack/verify-grpc.sh script
- add a ci job that runs "generate-grpc.sh" and then compares (diffs) content w/ verify-rpc.sh -> fails if different

/good-first-issue

**Comment by kanha-gupta** [comment]
Hi i would like to contribute
i am a newbie

**Comment by yashsingh74** [comment]
Open a PR- https://github.com/kubernetes-sigs/kpng/pull/285
