### ISSUE TITLE
Add a quick comment/link back to the service.go e2e

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/kpng#289]
The service.go e2e queries the kube proxy for the "type" of proxy as part of the way it tests... 

https://github.com/kubernetes/kubernetes/blob/b1e2af45e4ff126fcbcffa2e66ed36502103be7b/test/e2e/network/service.go#L3911

In cases where you dont have a kube proxy running, these tests dont run at all.. i.e. they are backend specific

We should comment why we run "servceProxyMode" for the future so that people looking at our backends understand its just for backwards compatibility w/ upstream e2es

Lets add a comment to ... 

https://github.com/kubernetes-sigs/kpng/blob/master/backends/ipvs-as-sink/ipvs.go#L287

**Comment by jayunit100** [comment]
good way to learn up about upstream e2es

**Comment by aahemm** [comment]
Hi @chetak123,
It seems that you are working on this issue right now. Please let me know if it is not the case. Thanks.

**Comment by chetak123** [comment]
yes I'll be making a PR soon for this issue
