### ISSUE TITLE
Update to 1.25

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/kpng#298]
Lets update the KPNG brain  to 1.25 ! were falling behind

initial testing indicating that were broken on 1.25 bc of beta removal of endpoints

**Comment by mcluseau** [comment]
AFAICT client-go is still 1.25 alpha:
```
[git/k/client-go] master $ git tag |grep '\.25\.'
kubernetes-1.25.0-alpha.0
kubernetes-1.25.0-alpha.1
kubernetes-1.25.0-alpha.2
v0.25.0-alpha.0
v0.25.0-alpha.1
v0.25.0-alpha.2
```
