### ISSUE TITLE
Table tests for kube-proxy

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/kpng#3]
We currently have some working going on with comparing old iptables/ipvs/... rules w/ those generated by KPNG.
As part of this, what we need is a way to generate table driven tests for various kube proxy permutations:

- Host Port Services
- NodePort local enabled / disabled 
- Loadbalancer services
- ClusterIP Services 
- NodePort services
- endpointSlices on / off

ideally if we could have a daemonset which was running, and which then polled every type of service from all nodes, we could generate a profile - which told us which types of services did/didn't work...

```
                               HostPort Service.        NodePort local          LoadbalancerService.    NodePort Service
pod-on-node1                 .1s
pod-on-node2                 .2s
pod-on-node3                 .2s
pod-on-node4                 .2
```

I think Doug is going to start prototyping such a test in bash, and then from there, we'll build it out in golang after testing it and generating a non-trivial set of verifications.

**Comment by mcluseau** [comment]
sure, the more we test conformity the better. I'm just not sure for endpoint slices, I feel like we should drop support for Endpoints in kpng, as it may already be well aligned with their deprecation (or at least the EndpointSlices being GA and not optional).
