### ISSUE TITLE
ebpf ci job

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/kpng#300]
Follow on to #292 , we'll need to build a Job, but it will fail (we know that) , because of these: 

- should be able to preserve UDP traffic when server pod cycles for a NodePort service 
- should be possible to connect to a service via ExternalIP when the external IP is not assigned to a node 
- [sig-network] Services �[0m�[91m�[1m[It] should be able to create a functioning NodePort service 
- [sig-network] Services should have session affinity timeout work for NodePort service
- [sig-network] Services should be rejected when no endpoints exist 
Services should be able to switch session affinity for service with type clusterIP Services 
- should be able to switch session affinity for NodePort service 
- Services should be able to change the type from ExternalName to NodePort 
- should serve multiport endpoints from pods
- should be able to update service type to NodePort listening on same port number but different protocols 
- should have session affinity work for service with type clusterIP 
- should have session affinity timeout work for service with type clusterIP [LinuxOnly] 
- should have session affinity work for NodePort service [LinuxOnly] [Conformance] �[0m

Then from there lets see if new folks want to work to help @astoycos harden the ebpf proxy over time by picking off one of these.

**Comment by astoycos** [comment]
Fixed by https://github.com/kubernetes-sigs/kpng/pull/309
