### ISSUE TITLE
figure out how to test clusterTraifficPolicy=cluster vs local,  in KPNG

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/kpng#305]
Looking at https://github.com/kubernetes-sigs/kpng/pull/287/
 
*possibly add new tests upstream (or see if theyre there already)*
 
- Talking to @mcluseau , he's trying to support the ability of the kpng proxy to make sure that it only uses local endpoints when "clusterTrafficPolicy=local".  

- to test this, we can make  a service w/ externalIP or NodePort to pull a servieEndpoint=local, where EACH ENDPOINT serves its nodename ... and you NEVER get more then one value.  This means theres zero node bounce forwarding occuring

- similar to https://github.com/kubernetes/kubernetes/pull/110967 , we might need a new upstream e2e not sure yet

- lets also ask the question, generally to upstream k8s sig 
```
Services [It] should preserve source pod IP for traffic thru service cluster
should we perserve source addresses for NODEPORTs
... when externalTrafficPolicy=local ????
``` 

( DONT DO THIS but, its just a note, theres another way test this..... (  setup a cluster where nodes cant forward traffic somehow , and see connection failures when using ) )

**Comment by jayunit100** [comment]
i.e. "services should not source NAT" - mc

**Comment by astoycos** [comment]
We should be able to test this with an extra "remote" container

**Comment by mcluseau** [comment]
@astoycos yes, I was thinking of a daemonset returning its nodeName ie over HTTP

**Comment by astoycos** [comment]
@mcluseau I can take a look at this :) we do something similar in ovn-kubernetes 

/assign

**Comment by astoycos** [comment]
I can still help here though please reach out if you need help!

**Comment by emabota** [comment]
Hi @astoycos , can you help/guide me on with this issue? Where should I start from?
