### ISSUE TITLE
Backends nft and ipvs can't handle hairpin

### ISSUE THREAD

**Issue by uablrek** [kubernetes-sigs/kpng#308]
K8s e2e-test;
```
[sig-network] Services should allow pods to hairpin back to themselves through services
# (suggested FOCUS='.*hairpin.back.to.themselves.*')
```

This test fails for backends;

* `nft`
* `ipvs`

but succeeds for backends `iptables`, `ebpf` and `userspacelin`.

**Comment by daman1807** [comment]
@jayunit100 the new IPVS backend handles hairpin traffic.
