### ISSUE TITLE
Add support for NodePort in kpng/ ebpf

### ISSUE THREAD

**Issue by srampal** [kubernetes-sigs/kpng#310]
Issue to track work for adding support for NodePort services in the eBpf backend of kpng.

**Comment by jayunit100** [comment]
Great to have you helping us flesh this out  thanks sanjeev

I know nodeports are tricky in eBPF can you add a few details to this issue on how well implement them?

**Comment by astoycos** [comment]
/cc @brunopecampos

If you'd like to pick this up we can dive in together, it's not super simple :)

**Comment by brunopecampos** [comment]
> /cc @brunopecampos
> 
> If you'd like to pick this up we can dive in together, it's not super simple :)

Thank you @astoycos. I'll have a look at the issue and the ebpf code.
I'll be asking you questions along the way :)
