### ISSUE TITLE
big scale test thats publically documented

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/kpng#325]
we need to do a big, public, open scale test of kpng on say, 50 nodes and leave it up for a week as part of de-risking any questions that come up in https://github.com/kubernetes/enhancements/pull/2094 

any company's willing to sponsor infra, please leave a note in here !

**Comment by jayunit100** [comment]
Were still looking for help here , if anyone on the Azure, EC2, GKE side wants to donate some infra let us know ! we only need it for a month!

**Comment by jayunit100** [comment]
Is there a a/b service proxying performance test that we can run ? @danwinship @astoycos

**Comment by ameukam** [comment]
@jayunit100 Can we get more details about technical requirements ? spec of a nodes ? for how long the scale test is supposed to run ? 24/7 ? only one test to run ?
