### ISSUE TITLE
backend agnostic reconciliation test

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/kpng#328]
we'd like something like https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/kube_proxy.go that we can use to run a/b comparisons in service of #325 

@astoycos is interested in this, seems like a simple way to do it would be 

```
make a service
for node in nodes:
   add 100 pods to the service
```

and then, say 1000 times

- modify pod count (scale up or scale down)

```
make 1000 go funcs:
  in parallel poll  the SEP until EACH ENDPOINT is obtained.
```

continuously.

**Comment by jayunit100** [comment]
/good-first-issue 

(For an experienced programmer that knows how to use client-go)

**Comment by mcluseau** [comment]
how far is taht from https://github.com/kubernetes-sigs/kpng/blob/master/server/cmd/kpng-backend-torture/main.go ?
Other refs:
- #150 
- `dist/kpng-backend-torture --listen unix:///tmp/kube-proxy.sock --sleep 1s 0:0 10000:10 10001:10 0:0 100000:1 0:0 1:100000` : 1s delay between diffs to the client, start with 0 services each with 0 endpoints, then 10k services with 10 endpoints, then 10k1 services with 10 endpoints, then back to 0:0, then 100k services with 1 endpoint, back to 0:0, then 1 service with 100k endpoints.
