### ISSUE TITLE
Prototype running kpng-windows in Containers 

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/kpng#330]
Currently the way we test is in process 

https://jayunit100.blogspot.com/2022/03/my-dev-workflow-for-kpng-windows.html?q=windows

However, @marosset has volunteered to get kpng windows backend working in a container (host process) which would be great !

To do this we'd need to 

- build the container
- containerize the `api=... to-winkernel`

**Comment by marosset** [comment]
https://github.com/kubernetes-sigs/kpng/pull/337

**Comment by jayunit100** [comment]
Still doing ths

**Comment by jayunit100** [comment]
this is done mark got it working.

**Comment by marosset** [comment]
We will pick this work up in k-sigs/windows-service-proxy
