### ISSUE TITLE
Backend ipvs only works on the local node

### ISSUE THREAD

**Issue by uablrek** [kubernetes-sigs/kpng#34]
When using the `ipvs` backend there is no masquerading when the call is routed to another node. So only calls to the local node works _from the main netns on the node_. There must be some rule that uses the `KUBE-MARK-MASQ` chain;

```
# iptables -t nat -S
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P OUTPUT ACCEPT
-P POSTROUTING ACCEPT
-N KUBE-KUBELET-CANARY
-N KUBE-MARK-DROP
-N KUBE-MARK-MASQ
-N KUBE-POSTROUTING
-A POSTROUTING -m comment --comment "kubernetes postrouting rules" -j KUBE-POSTROUTING
-A POSTROUTING -s 11.0.0.0/16 ! -d 11.0.0.0/16 -j MASQUERADE
-A KUBE-MARK-DROP -j MARK --set-xmark 0x8000/0x8000
-A KUBE-MARK-MASQ -j MARK --set-xmark 0x4000/0x4000
-A KUBE-POSTROUTING -m mark ! --mark 0x4000/0x4000 -j RETURN
-A KUBE-POSTROUTING -j MARK --set-xmark 0x4000/0x0
-A KUBE-POSTROUTING -m comment --comment "kubernetes service traffic requiring SNAT" -j MASQUERADE --random-fully
```

**Comment by jayunit100** [comment]
@knabben can we repro this in the new service tests?

**Comment by jayunit100** [comment]
```
.   x x
x  .  x
x  x  .
```

unless hairpin , in which case nothing works, but lars seems to be having success w hairpin

**Comment by mcluseau** [comment]
that's probably needs a better status assertion than rotten ;)

/remove-lifecycle rotten

**Comment by knabben** [comment]
SNAT was broke on OLD ipvs backend there wasn't ant chain rule marking 0x400 for the api service.. probably worth to bring a ci job for the new be
