### ISSUE TITLE
kpng w/ ebpf backend : Cluster DNS not working

### ISSUE THREAD

**Issue by srampal** [kubernetes-sigs/kpng#342]
I am trying out KPNG with the ebpf backend and running into a scenario where cluster DNS resolution doesnt seem to work.

This is with a Kind-kpng cluster on a Fedora 3.6 machine and 5.19 kernel
[vagrant@bnp-vm kpng]$ uname -r
5.19.4-200.fc36.x86_64

The symptom is that DNS resolution fails when resolving a k8s service name in some cases. I have a deployment of nginx pods that expose a clusterIP service and a client container running some networking utils. Running "curl nginx" on the client container fails but running "nslookup nginx" does work. I can see the DNS queries getting logged by the coredns pods when I enable them for logging but the resolution doesn't complete. SELinux and Firewalld were both configured disabled. Discussed this and additional details with @astoycos

**Comment by astoycos** [comment]
So this looks to be directly related to what node the client is on, curls always go from pod `tmp-shell3` -> service `nginx-default`

```
[astoycos@nfvsdn-02-oot kpng]$ kubectl get svc 
NAME               TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)   AGE
kubernetes         ClusterIP   10.2.0.1      <none>        443/TCP   175m
nginx-deployment   ClusterIP   10.2.219.25   <none>        80/TCP    153m
```

` curl 10.2.219.25` aways works 

`curl nginx-deployment` only works when client the client is on a different node for some reason

Works
```
[astoycos@nfvsdn-02-oot kpng]$ kubectl get pods -A -o wide
NAMESPACE            NAME                                                       READY   STATUS    RESTARTS   AGE    IP           NODE                               NOMINATED NODE   READINESS GATES
default              nginx-deployment-9456bbbf9-dh79c                           1/1     Running   0          150m   10.1.2.4     kpng-e2e-ipv4-ebpf-worker          <none>           <none>
default              nginx-deployment-9456bbbf9-stqfk                           1/1     Running   0          150m   10.1.1.2     kpng-e2e-ipv4-ebpf-worker2         <none>           <none>
default              tmp-shell3                                                 1/1     Running   0          15s    10.1.1.5     kpng-e2e-ipv4-ebpf-worker2         <none>           <none>

```

Doesn't work 
```
[astoycos@nfvsdn-02-oot kpng]$ kubectl get pods -A -o wide
NAMESPACE            NAME                                                       READY   STATUS    RESTARTS   AGE    IP           NODE                               NOMINATED NODE   READINESS GATES
default              nginx-deployment-9456bbbf9-dh79c                           1/1     Running   0          152m   10.1.2.4     kpng-e2e-ipv4-ebpf-worker          <none>           <none>
default              nginx-deployment-9456bbbf9-stqfk                           1/1     Running   0          152m   10.1.1.2     kpng-e2e-ipv4-ebpf-worker2         <none>           <none>
default              tmp-shell3                                                 1/1     Running   0          19s    10.1.2.9     kpng-e2e-ipv4-ebpf-worker          <none>           <none>

````

**Comment by srampal** [comment]
Not working in my setup regardless of same or different nodes .. (both cases below didn't work)

`[vagrant@bnp-vm kpng]$ kc get pods -o wide
NAME                               READY   STATUS    RESTARTS   AGE    IP         NODE                         NOMINATED NODE   READINESS GATES
nginx-deployment-9456bbbf9-m6gw7   1/1     Running   0          129m   10.1.2.3   kpng-e2e-ipv4-ebpf-worker2   <none>           <none>
tmp-shell                          1/1     Running   0          129m   10.1.1.5   kpng-e2e-ipv4-ebpf-worker    <none>           <none>`

`[vagrant@bnp-vm kpng]$ kc get pods -o wide
NAME                               READY   STATUS    RESTARTS   AGE    IP         NODE                        NOMINATED NODE   READINESS GATES
nginx-deployment-9456bbbf9-shb8l   1/1     Running   0          30s    10.1.1.6   kpng-e2e-ipv4-ebpf-worker   <none>           <none>
tmp-shell                          1/1     Running   0          135m   10.1.1.5   kpng-e2e-ipv4-ebpf-worker   <none>           <none>
[vagrant@bnp-vm kpng]$`
