### ISSUE TITLE
Promote an official KPNG image to `registry.k8s.io`

### ISSUE THREAD

**Issue by astoycos** [kubernetes-sigs/kpng#344]
External Users of KPNG need a way to get up to date images, we should therefore setup the infra to automatically push the KPNG docker image to `registry.k8s.io`. 

In general the Steps are as follows (to the best of my knowledge) 

1. Setup an official group for KPNG at https://github.com/kubernetes/k8s.io/blob/main/groups/sig-network/groups.yaml 
2. Make a Prow Job for the image pushing (see ingress-nginx one as an example https://github.com/kubernetes/test-infra/blob/master/config/jobs/image-pushing/k8s-staging-ingress-nginx.yaml)
3. Setup a Cloudbuild yaml in KPNG https://github.com/kubernetes/ingress-nginx/blob/main/cloudbuild.yaml

I might have missed something here but in general if there are questions you can refer to the way that ingress-nginx and the gateway-api got this done 
- [Ingress-nginx](https://github.com/kubernetes/ingress-nginx/pull/5578)
- [GatewayAPI](https://github.com/kubernetes-sigs/gateway-api/pull/621)

**Comment by ameukam** [comment]
cc

**Comment by marosset** [comment]
I can help with any parts of building the Windows container images.

**Comment by marosset** [comment]
/remove-lifecycle rotten

We have a job set up to push images to the staging repo but it looks like it is misconfigured :(
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-windows-service-proxy-push-images/1616506926940557312

I'll take a look soon

**Comment by liangyuanpeng** [comment]
Where can i find that message for knpg?

- email-id, like k8s-infra-push-cni@kubernetes.io
- members emails

/assign
