### ISSUE TITLE
add comprehensive prometheus metrics to kpng brain 

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/kpng#351]
We need to add comprehensive prometheus metrics to the brain, i.e.  so we can measure

- whenever it responds to a GRPC req
- whenever it is calling the APIserver , how long it takes before it recieves data
- etc... 

And to the kpng client (that lives on backends) so we can get

- info on whenever a diff is percieved
- how long it takes to read through all endpoints 
- how long insertes/updates take

And of course, we need to validate that existing metrics in backends (iptables for example) work
- how long it takes to write the iptables rules out
- how long it takes to respond to serviceUpdate, endpointsUpdate, ... 

most of all, we need a dashboard that ties this all together for our perf tests, or a blog post on how to use those metrics to profile kpng. 

This is a fun way to learn prometheus and the kpng codebase at the same time

/good-first-issue

**Comment by jayunit100** [comment]
this is a pretty hard first issue but, i think it would be a blast to work on

**Comment by jayunit100** [comment]
@astoycos did this over the wknd :)

**Comment by asim-reza** [comment]
Was swamped with work sorry

**Comment by jayunit100** [comment]
no problem he can push the initial up and then we can iteratively add new metrics

/assign @astoycos
