### ISSUE TITLE
lets format the code in ci

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/kpng#377]
@astoycos thinks were CRAZY bc we dont `gofmt` EVERY SINGLE PR

lets make him happy :) 

files to impl
```
hack/verify-gofmt.sh
hack/update-gofmt.sh
https://github.com/kubernetes-sigs/kpng/blob/master/.github/workflows/vet-code.yml
```

**Comment by heisaman** [comment]
I'll fix it. 😃

**Comment by uablrek** [comment]
Please remember;

### CI or any plugin MUST NOT update the repository itself!

It may seem loke a cool idea but _will_ come back and bite you in some way. Do as K8s, have a format test in CI that fails.

**Comment by uablrek** [comment]
For instance;
an update trigs an event -> the event updates the repo -> an update trigs an event -> ...

If you have more than one event that updates the code this is likely, and will ruin your day.

**Comment by abhishek44sharma** [comment]
@gitvinit are you working on this?

**Comment by gitvinit** [comment]
This should be done with PR: https://github.com/kubernetes-sigs/kpng/pull/485

**Comment by liangyuanpeng** [comment]
So this issue should be closed.
