### ISSUE TITLE
Make makefile more idempotent / maybe Make it a taskfile (begginer issue)

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/kpng#378]
Intentionally leaving this vauge: Whoever picks it up can chose how to do it.  Fun issue to start with .   Either

-  fix the makefile targets so they all work OOTB (for example by running `eval "$(curl -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme | GIMME_GO_VERSION=1.18beta1 bash)"` beforehand ... or confirming GOLang version... 
- in the process if folks want to get rid of make targets and replace them w/ a Taskfile (taskfile.dev) , and make those work ootb , thats find to

Can someone get these targets all functioning ? or maybe even rewrite it as a https://taskfile.dev/ 

/good-first-issue

**Comment by emabota** [comment]
/assign 
Hi @adityadtu5, are you still working on this issue? Have you come up with a plan/idea for how to work on it? Are you going to stick with makefiles or rewrite it in taskfiles?

**Comment by jayunit100** [comment]
for now, i think running targets one at a time and seeing what works/doesnt and fixing them is a good start.  then can decide on the taskfile part later if we want it

**Comment by brunopecampos** [comment]
/assign
I'll add some an error when trying to run make tilt-up without previously running make tilt-setup.
