### ISSUE TITLE
WINDOWS Implement kernelspace fullstate backend

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/kpng#393]
Looked at the NFT code today w/ @papagalu , we think a windows backend will be alot 
more easy to understand if we build it iteratively. 

Lets start by  , without using diffstore, building a stateless windows fullstate backend and see how it works. 

Then from there we can add diffstore in secondarily.

Roughly this involves:
- taking nft.go, copying it over, removing nftables refs, implementing `Callback...`
- implementing the register.go, which will create the backend client....  
```
type backend struct {
	cfg localsink.Config
}

func init() {
	backendcmd.Register("to-nft", func() backendcmd.Cmd { return &backend{} })
}

func (b *backend) BindFlags(flags *pflag.FlagSet) {
	b.cfg.BindFlags(flags)
	BindFlags(flags)
}

func (b *backend) Sink() localsink.Sink {
	sink := fullstate.New(&b.cfg)

	PreRun()

	ct := conntrack.New()
	sink.Callback = fullstatepipe.New(fullstatepipe.ParallelSendSequenceClose,
		Callback,
		ct.Callback,
	).Callback

	return sink
}
```
- adding `_ "sigs.k8s.io/kpng/backends/windows/fullstate"` to storecmds_windows.go so that it registers the command as a backend store
- 

For testing, we can use sig-windows-dev-tools.  We'll may have to make aPR to it to start calico/antrea WITHOUT starting AntreaProxy/KubeProxy.... in that case, we'd need 
to start antrea/calico with a direct IP 
address to the APIServer (10.20.30.10, or whatever)...

**Comment by daman1807** [comment]
@jayunit100 should we close this one? 
this can be part of win-proxy repo

**Comment by jayunit100** [comment]
Ya closeeeee it's done anyways
