### ISSUE TITLE
e2e test suite fails but job succeeds

### ISSUE THREAD

**Issue by aojea** [kubernetes-sigs/kpng#400]
```
Summarizing 2 Failures:
  [FAIL] [sig-network] Services [It] should be updated after adding or deleting ports 
  test/e2e/network/service.go:966
  [FAIL] [sig-network] Services [It] should serve multiport endpoints from pods  [Conformance]
  test/e2e/network/service.go:922

Ran 306 of 7067 Specs in 666.762 seconds
FAIL! -- 304 Passed | 2 Failed | 0 Pending | 6761 Skipped


Ginkgo ran 1 suite in 11m11.265497035s

Test Suite Failed
```

However, the job is green https://github.com/kubernetes-sigs/kpng/actions/runs/3584852487/jobs/6032067673

???

**Comment by jayunit100** [comment]
ahhh  so, yes, we want to "pass" because its not a regression, but i see what you mean . 

Should we add a separate (non-blocking) test that runs these 2 known failure cases ? or just make it fail every time ?

**Comment by aojea** [comment]
those tests are exercising common functionality of Services, not having them passing means that kpng is not complaint, if you really want to offer kpng to users those test have to be passing
