### ISSUE TITLE
NFT Proxy should send the node name

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/kpng#410]
@daman1807 showed me  this recently when making ipvs to fullstate... the NFT proxy doesnt send the node name when registering.

- we should error in the brain when the backend doesnt send this on register
- we should fix the issue in the NFT backend also
- part of why i filed this issue was so that i could say the word "brain"

**Comment by daman1807** [comment]
@jayunit100 we should definitely add that to the "**brain**". 

Current Registration 

```
type backend struct {
	cfg localsink.Config
}

func init() {
	backendcmd.Register("to-nft", func() backendcmd.Cmd { return &backend{} })
}
```

Possible Fix
```
hostname, err := os.Hostname()
return &backend{
        cfg: localsink.Config{NodeName: hostname},
}
```

**Comment by emabota** [comment]
/assign 
Hi. If this is a beginner issue or it doesn't require expertise in Go, count me in!

**Comment by mcluseau** [comment]
`backendcmd.Cmd` provides `BindFlags` which calls the one from `localsink.Config` (https://github.com/kubernetes-sigs/kpng/blob/master/backends/nft/register.go#L38), which itself defaults to the hostname (https://github.com/kubernetes-sigs/kpng/blob/1b5bb66788498c660028885aa583400da7b9aecf/client/localsink/localsink.go#L45).

So, I'm still skeptical about this issue, that could come from an override to "empty" in the deployment (daemonset).

**Comment by daman1807** [comment]
@mcluseau I logged all the **localv1.Endpoint** received in the callback and none of them were local, my understanding is that ***localv1.Endpoint.Local** is determined by the node name. Maybe @emabota can check whether it is being overridden or not?

**Comment by emabota** [comment]
@daman1807 how can I check that? What should I look for?

**Comment by jayunit100** [comment]
i guess we should check unit tests here
