### ISSUE TITLE
 local-up-kpng.sh  CI job smoke test

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/kpng#420]
lets run local-up-kpng.sh in a github action , otherwise some of the args it uses etc might not be properly supported.

**Comment by emabota** [comment]
Hi @jayunit100 I have a PR for this issue #466 . 
Though I don't understand what you mean by "... otherwise some of the args it uses etc might not be properly supported". Let me know if the PR as it is safeguard your requirements about the args.
