### ISSUE TITLE
(debatable) remove iptables and windows kernel proxy 

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/kpng#422]
- We now will have an out of tree windows kernel proxy
- iptables is going to live in tree and eventually be replaced by NFT probabl

# Why move out the most common proxy impl? 

- In initial backends we tried to mimic all of upstream (by adding / copying other proxies).  This was to gain traction and prove that KPNG works broadly. 
- Now the goal shifts towards : implementing things not implemented in the in-tree proxy... bc its likely iptables , in tree, will never really go away.  And the bigger benefit is new proxies (windows, nft, ebpf,...) that are forward looking. 
 

... This is roughly a conclusion from a recent KPNG meeting we had.  

But if there are other opinions feel free to add here.

**Comment by knabben** [comment]
/remove-lifecycle stale

Windows kernel proxy is already on repo: https://github.com/kubernetes-sigs/windows-service-proxy
