### ISSUE TITLE
Disable kube-proxy in CI e2e tests

### ISSUE THREAD

**Issue by aryan9600** [kubernetes-sigs/kpng#425]
The kind cluster created for e2e tests in CI doesn't seem to have its kube-proxy disabled (ref: https://github.com/kubernetes-sigs/kpng/blob/master/hack/test_e2e.sh#L228-L238), like it should be, which makes the tests unreliable.

**Comment by jaehnri** [comment]
Hi, @aryan9600!
Locally, I wasn't able to reproduce this issue, i.e., see that `kube-proxy` is enabled. One example:
```bash

$ ./hack/test_e2e.sh -i ipv4 -b ipvs -d

...

+=====================================================================================+
                Developer mode no test run!
+=====================================================================================+

$ kubectl get pods -n kube-system
NAME                                                       READY   STATUS    RESTARTS   AGE
coredns-565d847f94-nw577                                   1/1     Running   0          44s
coredns-565d847f94-wfclq                                   1/1     Running   0          44s
etcd-kpng-e2e-ipv4-ipvs-control-plane                      1/1     Running   0          60s
kindnet-598ln                                              1/1     Running   0          45s
kindnet-ft8v2                                              1/1     Running   0          37s
kindnet-t7bx9                                              1/1     Running   0          37s
kpng-6jfzc                                                 1/1     Running   0          26s
kpng-hqrhq                                                 1/1     Running   0          26s
kpng-k7j5g                                                 1/1     Running   0          26s
kube-apiserver-kpng-e2e-ipv4-ipvs-control-plane            1/1     Running   0          61s
kube-controller-manager-kpng-e2e-ipv4-ipvs-control-plane   1/1     Running   0          58s
kube-scheduler-kpng-e2e-ipv4-ipvs-control-plane            1/1     Running   0          58s
```

Could you point me to the correct way, please? Thank you :)

**Comment by aryan9600** [comment]
i'm sorry, this issue isn't completely correct, it seems like we are manually deleting kube-proxy after creating the cluster: https://github.com/kubernetes-sigs/kpng/blob/f2a7eb815a9a7fe5eb8fa8e4e54cc7b0ae6df2a6/hack/test_e2e.sh#L357-L360
instead of just disabling it in the first place like we do here:
https://github.com/kubernetes-sigs/kpng/blob/f2a7eb815a9a7fe5eb8fa8e4e54cc7b0ae6df2a6/hack/kind.yaml#L5
@jayunit100 any idea why are we doing this?

**Comment by jayunit100** [comment]
I hope we're not doing this by necessity :) no idea why .....

Let's disable on boot and see what breaks
