### ISSUE TITLE
NFT doesnt work w sessionAffinity 

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/kpng#434]
I dont know what this issue is about but @qabpea didnt file it so i am :)

**Comment by qabpea** [comment]
I am still working on running the e2e tests in a loop to make sure I have identified all existing problems, check test_e2e.sh and you get a pretty good idea by looking at the different variables that defines which tests that must be skipped for the ci/cd tests to run clean

**Comment by jayunit100** [comment]
Can someone validate NFT w/ session Affinity?

**Comment by qabpea** [comment]
I am looking at uplifting to latest k8s, I can look at NFT at the same time.
both v4 and v6?

//Per
