### ISSUE TITLE
Not possible to upgrade to Kubernetes version 1.26.0

### ISSUE THREAD

**Issue by qabpea** [kubernetes-sigs/kpng#442]
This issue is connected to PR #440 . The problem is github workflow environment specific.
Check the test records for all the ipvs backend e2e_test runs. ginkgo in combination of IPVS does not work for some reason. @aojea do you have any idea/suggestion what may cause this?

Ignore the userspacelin test failure, this is just another e2e test case that must be added to the skip lists

**Comment by aojea** [comment]
can you share a link to the logs?

**Comment by qabpea** [comment]
This run did not give any good runs
https://github.com/kubernetes-sigs/kpng/actions/runs/4032423705/jobs/6932293826

All of them timed out, I will try to run it a couple of more times within the PR.

**Comment by aojea** [comment]
the ipvs pod fails to start with the following error
```
2023-01-28T17:03:11.858594463Z stderr F I0128 17:03:11.858529       1 ipvs.go:137] AddIP (svc: Namespace:"default"  Name:"kubernetes"  Type:"ClusterIP"  IPs:{ClusterIPs:{V4:"10.2.0.1"}  ExternalIPs:{}}  Ports:{Name:"https"  Protocol:TCP  Port:443  TargetPort:6443}, svc-ip: 10.2.0.1, type: ClusterIP)
2023-01-28T17:03:11.858599963Z stderr F F0128 17:03:11.858571       1 ipvs.go:396] exit early while adding dummy IP %!(EXTRA string=10.2.0.1/32, string=; dummy link device not found)
```

**Comment by qabpea** [comment]
Why would that happen when switching to 1.26.0? Weird

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by uablrek** [comment]
The kube-proxy no longer explicitly loads ipvs kernel modules, please see https://github.com/kubernetes/kubernetes/pull/114669.

Is it possible that kpng relies on that kube-proxy is loaded, but not used, to trig module loading?

Anyway, kpng should do the same as kube-proxy: test the ipvs _function_ (_**NOT**_ load a module!).

**Comment by uablrek** [comment]
I see I have already reported this in https://github.com/kubernetes-sigs/kpng/issues/311 :smiley:

**Comment by daman1807** [comment]
thanks, @uablrek 
will try that out

**Comment by uablrek** [comment]
> Perhaps, probably best to add the mod probe into where the we setup the kind node.

That would be to put the responsibility to make sure ipvs is available on the node owner. IMO a bad idea, and unnecessary. A simple check as described in https://github.com/kubernetes-sigs/kpng/issues/311 shall be made by the ipvs backend at startup. It is very simple, and serves two purposes:

1. Ensure ipvs is available on the system (may be a statically linked kernel, or module based, doesn't matter)
2. Load the module(s) automatically if necessary

The second is a fundamental function in Linux, e.g you don't have to explicitly load add iptables modules you use. The kernel makes an up-call to `/proc/sys/kernel/modprobe`. For experiments you may set your own hook, but don't do that on you own host, use a VM :smile: 

```
> cat /proc/sys/kernel/modprobe
/sbin/modprobe
```

**Comment by uablrek** [comment]
Please, [also consider](https://github.com/kubernetes-sigs/kpng/issues/311#issuecomment-1294471557):

> As a side remark, kpng MUST NOT set sysctls. That is the main reason why the kube-proxy container can't run unprivileged.

A common trick is to set all sysctls you _really need_ in a privileged initContainer.

**Comment by mcluseau** [comment]
by the same logic, modprobe should also be run a privileged init container

**Comment by uablrek** [comment]
By the logic above, modprobe should not be run at all!
