### ISSUE TITLE
finish the prometheus work

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/kpng#470]
we now have prometheus metrics , but we havent yet automated their deployment in kpng-local-up.sh.  LEts make sure:

- the KPNG client publishes metrics
- that we scrape the KPNG brain 
- We launch prometheus https://github.com/prometheus-operator/prometheus-operator on startup of KPNG and toggle it to scrape the KPNG services

ideally we should be able to make pretty pictures that show for example how many add,sync,watch,opitem types and so on are triggered so that we can use it to instrospect how adding large amounts of services/endpoints work

**Comment by jaehnri** [comment]
/assign

@emabota, lmk what you're working on so we can split this work. Ping me in Slack if you prefer

**Comment by emabota** [comment]
Hi @jaehnri, I haven't started working on this yet. Go ahead, pick whichever you want!

**Comment by adeniyistephen** [comment]
/assign

@jaehnri are you already working on this issue? if yes or no, I would like to help out and contribute.

**Comment by Asiya-Yunusa** [comment]
Hello @adeniyistephen and @jaehnri Iwill like to help out and contribute

**Comment by adeniyistephen** [comment]
awesome, let's just wait for @jaehnri to reach out back,

**Comment by jaehnri** [comment]
I haven't really started it. @Asiya-Yunusa @adeniyistephen, you can go ahead and pick it up.

/unassign

**Comment by Asiya-Yunusa** [comment]
@adeniyistephen when can we start please?

**Comment by adeniyistephen** [comment]
sure, you can go ahead and read on the task, I'll do the same too - and we can discuss our findings/understanding on Slack by tomorrow.

**Comment by jayunit100** [comment]
partially done but nobody has confirmed we have comprehensive metrics for the op_items etc yet

**Comment by adeniyistephen** [comment]
@jayunit100 Nice one, I would run it and see how it looks. I don't know if I'm missing something, but I can't find ClusterRole system:auth-delegator. https://github.com/kubernetes-sigs/kpng/blob/3cb507a18ac1fd8c3f6f2fdb51ee4a3dbcdf7c42/hack/metrics/metrics-server.yaml#L81

**Comment by mattfenwick** [comment]
hi everybody , I started on this last week , merged some changes and have some more in the pipeline => will post in slack when I have some nice e2e stuff to look at !  ( should be soon )
