### ISSUE TITLE
broadly investigate the NFT errors on ipv6

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/kpng#472]
https://github.com/kubernetes-sigs/kpng/blob/master/hack/test_skip_list.sh#L138

Seems to highlight LOTS of NFT errors on ipv6... 

Are they all related. ?

**Comment by knabben** [comment]
Run the test_e2e.sh script locally with nft backend and IPv6 set, use GINKGO_FOCUS with one the SKIPPED test for example
`GIKGO_FOCUS="should work after the service has been recreated"`, and fill out the error on an issue or try to fix it directly.
