### ISSUE TITLE
comprehensive comments/docs on the Endpoints client and the kpng/client/client.go

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/kpng#484]
The *EndpointsClient* is a little confusing to read.  

- I THINK It doesnt specifically filter on endpoints, and in any case, we have endpointslices, services, and endpoints, which i believe it filters and watches on.  

- Also it doesnt say much about how the watch mechanism works and how its node specific

```
// doesnt EndpointsClient watch everything ? it sais its just a client to the endpoints API...
// EndpointsClient is a simple client to kube-proxy's Endpoints API.
type EndpointsClient struct {
	// Target is the gRPC dial target
	Target string
```

**Comment by mcluseau** [comment]
@jayunit100 it's the client for the Local API, formerly known as the Endpoints API in kpng. It can be renamed to LocalClient. Since it's the kpng API, there's no concept of EndpointSlice ;-)

**Comment by jayunit100** [comment]
sgtm ya LocalClient
