### ISSUE TITLE
GH Actions tests (but lets keep mob testing also)

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/kpng#50]
imo testing every friday  as a group is a good routine --- 
 but we should have some bot tests just to make @aojea happy :) also

UPDATE

To get started, go into every file w a go.mod and run 
```
GOOS=linux go build -o kpng ./kpng
```
in GH Actions 
@FriedrichWilken

**Comment by jayunit100** [comment]
as a starting point

- backend_torture.go
- https://github.com/K8sbykeshed/k8s-service-lb-validator/ 
- sonobuoy `sig-network` 
- sonobuoy `Conformance`

should be good enough but we can skip some tests (dualstack) and so onthat arent implemented yet

**Comment by aojea** [comment]
> but we should have some bot tests just to make @aojea happy :) also

users will be happier than me ...

**Comment by mcluseau** [comment]
I've set a basic GitHub action to run the go tests, that a first thing ;)

**Comment by jayunit100** [comment]
@rajaskakodar

**Comment by hanlins** [comment]
Testing is important, let me see what I can do...
/assign

**Comment by jayunit100** [comment]
thanks Hanlins we missed you !!!!!!

**Comment by FriedrichWilken** [comment]
https://github.com/kubernetes-sigs/kpng/pull/85

**Comment by jayunit100** [comment]
this is done now thanks to friedrich and neha !
