### ISSUE TITLE
Context (ctx) is used in a non-idiomatic way

### ISSUE THREAD

**Issue by uablrek** [kubernetes-sigs/kpng#518]
### What kind of issue is this?

/kind bug
/kind cleanup
/kind api-change

### Expected behaviour

As described in the [go documentation](https://pkg.go.dev/context) there are rules on how `context` shall be used. First an foremost:

> Do not store Contexts inside a struct type; instead, pass a Context explicitly to each function that needs it. The Context should be the first parameter, typically named ctx

### Actual behaviour

So far I have only checked https://pkg.go.dev/sigs.k8s.io/kpng/client, but I suspect the same pattern is used elsewhere in `kpng` code.

The context is stored in the `LocalClient` structure:

https://github.com/kubernetes-sigs/kpng/blob/8a78a86a9e451a0b89fa749aa9746ff4ead4cab0/client/client.go#L73-L76

This enforces a number of methods to get and configure the context. To avoid the need for those is likely a main reason for the rule. The problem becomes particularly apparent when an inherited function actually does the right thing, and pass `ctx context` as first parameter:

https://github.com/kubernetes-sigs/kpng/blob/8a78a86a9e451a0b89fa749aa9746ff4ead4cab0/client/client.go#L165-L181

Here the passed context is not used, but instead the one stored in the structure.

#### Passing data in the context

_This is a very important use-case of context!_ And the current pattern makes it impossible.

For instance modern implementations of structured logging, like [logr](https://github.com/go-logr/logr) and [klog](https://pkg.go.dev/k8s.io/klog/v2), passes the "logger" in the context ([FromContext()](https://pkg.go.dev/k8s.io/klog/v2#FromContext))

### Steps to reproduce the problem

N/A

**Comment by mcluseau** [comment]
well... I guess it depends on the context ;-)
 https://cs.opensource.google/go/go/+/refs/tags/go1.20.6:src/net/http/request.go;l=326

**Comment by uablrek** [comment]
Actually, I think this is a compromise. Net/http came _long_ before `context`, to do things "right" would break compatibility for the API. Kpng have the possibility to do it right since there are no releases yet. Also the `Run()` function (and likely others) should take a context (and honor it).
