### ISSUE TITLE
github actions updates and docs

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/kpng#524]
*This is not a "write a bunch of code" task but it is essential, so please expect to spend 2 to 3 weeks on this if you are a new contributor, and only self assign if you have the time to complete it as it might require coordinating several conversations/asking questions in different forums*

Looks like we've got some tech debt around the lifecycle for our github actions . 
 See #522 ... as an example.

Original thread https://kubernetes.slack.com/archives/C02GA1RSCLR/p1692815992205469 ...

- We want them to run for every PR when a PR happens
- We want them to run before merges happen
- We want them to pass for PRs that dont make breaking changes

Can someone verify this for us and update our README with a guide for how our CI is currently working? As a starting point:

- clone this repo, 
- look at the .github actions and understand them (ask question sin the sig-network-kpng slack channel if not sure what things are doing, cc @friedrichwilken  or @aroradaman or me 
- Go to the sig-testing weekly meeting to get an understanding if wanting to understand how / when github actions are triggered on new PRs (from K8s members? what about from non K8s members? How are the actions triggered differently) ? 

/good-first-issue

**Comment by aroradaman** [comment]
Currently, the GitHub actions are only being triggered when PR has **approved** and **lgtm** labels. 
We would love to have them triggered without any dependency on these two labels.

**Comment by FZhg** [comment]
Hi @aroradaman, I want to work on this! I have enough time. I have read the thread as well. This is my first time to contribute to k8s!  🐳  /assign

**Comment by FZhg** [comment]
Hi @jayunit100, could you give me a reference that how the CI guide should look like? Also, Should I check the Prow documentation for verifying the current behavior of  the `ok-to-test` label?

**Comment by aroradaman** [comment]
@FZhg

> Currently, the GitHub actions are only being triggered when PR has approved and lgtm labels.
We would love to have them triggered without any dependency on these two labels.

**Comment by FZhg** [comment]
> @FZhg
> 
> > Currently, the GitHub actions are only being triggered when PR has approved and lgtm labels.
> > We would love to have them triggered without any dependency on these two labels.

Thanks! I now understand the issue. We have 2 things to do:

**Comment by sbueringer** [comment]
This CAPI action might be useful https://github.com/kubernetes-sigs/cluster-api/blob/main/.github/workflows/pr-gh-workflow-approve.yaml

**Comment by FZhg** [comment]
Hi, @aroradaman! I have gone through the gh action files and found out that besides `docker-action.yml` , these files just runs different scripts in the hack directory.
