### ISSUE TITLE
Blog plost / Article: "next generation proxying with KPNG"

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/kpng#62]
This would be a good kpng demo for a newcomer to the project to writeup/publish.

1) define configs for separate machines (vagrantfile)
2) Start one kpng frontend
2) create 2 services w/ names a,b
3) start one kpng backend to focus on `service-proxy-name=a`,  (nft / ipvs)
4) start a second kpng backend to focus on `service-proxy-name=b`, (iptables) 
5) confirm that the backends work properly

**Comment by uablrek** [comment]
Please see; https://github.com/kubernetes/website/pull/29783

As you may know my primary interrest is to use `kpng` to write specialized proxiers, so this blog is about that :smile:

**Comment by uablrek** [comment]
Blog published https://kubernetes.io/blog/2021/10/18/use-kpng-to-write-specialized-kube-proxiers/

/close
