### ISSUE TITLE
ExternalLoadBalancer IPs support

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/kpng#68]
![image](https://user-images.githubusercontent.com/826111/132888638-34c6ce7a-922b-451b-bb7e-40491e9a02c6.png)
originally some confusion around #60 ... 

IMO from todays meeting we should
- (most important) We also should have a datamodel 
```
type ServiceStatus struct {
	LoadBalancer LoadBalancerStatus `json:"loadBalancer,omitempty" protobuf:"bytes,1,opt,name=loadBalancer"`
}
type LoadBalancerStatus struct {
	Ingress []LoadBalancerIngress `json:"ingress,omitempty" protobuf:"bytes,1,rep,name=ingress"`
}
```
- (less important) Namespace legacy concepts like `ExternalIP` in kpng if we use them, i.e. `K8sExternalIP` 
```
	ExternalIPs []string `json:"externalIPs,omitempty" protobuf:"bytes,5,rep,name=externalIPs"`
```
- (even less important??) need to figure out how to designate / should we support should make sure we have really good support in place for LoadBalancer IPs, 
```
	LoadBalancerIP string `json:"loadBalancerIP,omitempty" protobuf:"bytes,8,opt,name=loadBalancerIP"`
```

**Comment by uablrek** [comment]
the `service.spec.loadBalancerIP` is not a concern for `kpng`, nor `kube-proxy`. It is a hint to cloud-providers.

**Comment by uablrek** [comment]
svc.Spec.ExternalIPs and svc.Status.LoadBalancer.Ingress can not be merged into the same array. They must be handled separately if `kpng` should be compatible with `kube-proxy`. There is a proposal to disable load-balancing (setup by kube-proxy) for svc.Status.LoadBalancer.Ingress addresses in clusters where (external) load-balancing to nodePorts is used (couldn't find the issue now). But load-balancing for `ExternalIPs` should always be setup.
