### ISSUE TITLE
Compiling KPNG on Windows

### ISSUE THREAD

**Issue by knabben** [kubernetes-sigs/kpng#81]
```
$ cd cmd/
$ GOOS=windows go build ./kpng/...                          
``` 
Raises the following error:

```                                                                                                                                                                        
go build github.com/google/seesaw/ipvs: build constraints exclude all Go files in /home/knabben/go/pkg/mod/github.com/google/seesaw@v0.0.0-20210205180622-915f447b8ed8/ipvs
# github.com/vishvananda/netns
../../../../pkg/mod/github.com/vishvananda/netns@v0.0.0-20210104183010-2eb08e3e575f/netns.go:28:13: undefined: unix.Stat_t
../../../../pkg/mod/github.com/vishvananda/netns@v0.0.0-20210104183010-2eb08e3e575f/netns.go:29:12: undefined: unix.Fstat
../../../../pkg/mod/github.com/vishvananda/netns@v0.0.0-20210104183010-2eb08e3e575f/netns.go:32:12: undefined: unix.Fstat
../../../../pkg/mod/github.com/vishvananda/netns@v0.0.0-20210104183010-2eb08e3e575f/netns.go:43:8: undefined: unix.Stat_t
../../../../pkg/mod/github.com/vishvananda/netns@v0.0.0-20210104183010-2eb08e3e575f/netns.go:44:12: undefined: unix.Fstat
../../../../pkg/mod/github.com/vishvananda/netns@v0.0.0-20210104183010-2eb08e3e575f/netns.go:56:8: undefined: unix.Stat_t
../../../../pkg/mod/github.com/vishvananda/netns@v0.0.0-20210104183010-2eb08e3e575f/netns.go:57:12: undefined: unix.Fstat
../../../../pkg/mod/github.com/vishvananda/netns@v0.0.0-20210104183010-2eb08e3e575f/netns.go:71:12: undefined: unix.Close
# sigs.k8s.io/kpng/server/pkg/server
../server/pkg/server/server.go:42:15: undefined: syscall.Umask
../server/pkg/server/server.go:43:26: undefined: syscall.Umask
```

**Comment by FriedrichWilken** [comment]
I just started to work on [GitHub Actions](https://github.com/kubernetes-sigs/kpng/pull/85) to test the building of backend packages. Should I add some more for building from /cmd/ on linux, win and macos?

**Comment by knabben** [comment]
cc @dougsland

**Comment by dougsland** [comment]
@knabben nice, looks like kpng improved a lot. Today I don't see the errors. I still thing we should move ahead with: https://github.com/kubernetes-sigs/kpng/pull/219 WDYT?

**Comment by knabben** [comment]
> @knabben nice, looks like kpng improved a lot. Today I don't see the errors. I still thing we should move ahead with: https://github.com/kubernetes-sigs/kpng/pull/219 WDYT?

#219 is not related with this issue.

If the command runs with the registry of windows and Linux backends. I'm going to close it.

/close

**Comment by knabben** [comment]
> I just started to work on [GitHub Actions](https://github.com/kubernetes-sigs/kpng/pull/85) to test the building of backend packages. Should I add some more for building from /cmd/ on linux, win and macos?

#219 this is though. @fredkan can have more information of how it's going maybe..

**Comment by rajaskakodkar** [comment]
@dougsland thanks for opening #219. I think @nehaLohia27 can take over and get it to completion. WDYT?

cc: @jayunit100 @knabben

**Comment by dougsland** [comment]
> @dougsland thanks for opening #219. I think @nehaLohia27 can take over and get it to completion. WDYT?

Sure thing! @nehaLohia27 welcome aboard!
