### ISSUE TITLE
decompose hack/kpng-local-up.sh into separate scripts

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/kpng#96]
- `build.sh` (compile all of the kpng backends OR one of them as arg)
- `test-unit.sh`
- `test-conformance.sh` (run sonobuoy on a local kind cluster ... takes `backend` as optional arg) calls `hack/local-up-kpng.sh` under the hood and then runs sonobuoy.

**Comment by jayunit100** [comment]
for v0 of friedichs CI , just 
- make a hack/`build.sh`  script 
- ghave your gh actions call `hack/build.sh iptables` and then `hack/build.sh nft` and so on...

**Comment by FriedrichWilken** [comment]
- [x]      `build.sh` (compile all of the kpng backends OR one of them as arg)

- [x]      `test-unit.sh`

- [ ]      `test-conformance.sh` (run sonobuoy on a local kind cluster ... takes `backend` as optional arg) calls `hack/local-up-kpng.sh` under the hood and then runs sonobuoy.
